version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter channel stable
      - run: cd Client/Main/crypto_contest && flutter -v build apk --debug