import 'package:flutter/material.dart';

final ThemeData myTheme = ThemeData(
  primarySwatch: const MaterialColor(4294920469, {
    50: const Color(0xffffebe5),
    100: const Color(0xffffd7cc),
    200: const Color(0xffffb099),
    300: const Color(0xffff8866),
    400: const Color(0xffff6033),
    500: const Color(0xffff3900),
    600: const Color(0xffcc2d00),
    700: const Color(0xff992200),
    800: const Color(0xff661700),
    900: const Color(0xff330b00)
  }),
  brightness: Brightness.light,
  primaryColor: const Color(0xffff4915),
  primaryColorBrightness: Brightness.dark,
  primaryColorLight: const Color(0xffffd7cc),
  primaryColorDark: const Color(0xff992200),
  accentColor: const Color(0xffff3900),
  accentColorBrightness: Brightness.dark,
  canvasColor: const Color(0xfffafafa),
  scaffoldBackgroundColor: const Color(0xfffafafa),
  bottomAppBarColor: const Color(0xffffffff),
  cardColor: const Color(0xffffffff),
  dividerColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  splashColor: const Color(0x66c8c8c8),
  selectedRowColor: const Color(0xfff5f5f5),
  unselectedWidgetColor: const Color(0x8a000000),
  disabledColor: const Color(0xffe9e9e9),
  buttonColor: const Color(0xffff9800),
  toggleableActiveColor: const Color(0xffcc2d00),
  secondaryHeaderColor: const Color(0xffffebe5),
  textSelectionColor: const Color(0xffffb099),
  cursorColor: const Color(0xff4285f4),
  textSelectionHandleColor: const Color(0xffff8866),
  backgroundColor: const Color(0xffffb099),
  dialogBackgroundColor: const Color(0xffffffff),
  indicatorColor: const Color(0xffff3900),
  hintColor: const Color(0x8a000000),
  errorColor: const Color(0xffd32f2f),
  buttonTheme: const ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 128.0,
    height: 36.0,
    padding: const EdgeInsets.only(top: 0.0, bottom: 0.0, left: 16.0, right: 16.0),
    shape: RoundedRectangleBorder(
      side: const BorderSide(
        color: const Color(0xff000000),
        width: 0.0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    alignedDropdown: false,
    buttonColor: const Color(0xffff9800),
    disabledColor: const Color(0xffe9e9e9),
    highlightColor: const Color(0x29000000),
    splashColor: const Color(0x1f000000),
    colorScheme: ColorScheme(
      primary: const Color(0xffff4915),
      primaryVariant: const Color(0xff992200),
      secondary: const Color(0xffff3900),
      secondaryVariant: const Color(0xff992200),
      surface: const Color(0xffffffff),
      background: const Color(0xffffb099),
      error: const Color(0xffd32f2f),
      onPrimary: const Color(0xffffffff),
      onSecondary: const Color(0xffffffff),
      onSurface: const Color(0xff000000),
      onBackground: const Color(0xffffffff),
      onError: const Color(0xffffffff),
      brightness: Brightness.light,
    ),
  ),
  textTheme: const TextTheme(
    display4: const TextStyle(
      color: const Color(0x8a000000),
      fontSize: 96.0,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
    ),
    display3: const TextStyle(
      color: const Color(0x8a000000),
      fontSize: 60.0,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
    ),
    display2: const TextStyle(
      color: const Color(0x8a000000),
      fontSize: 48.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    display1: const TextStyle(
      color: const Color(0x8a000000),
      fontSize: 34.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    headline: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 24.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    title: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 20.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    subhead: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    body2: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    body1: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    caption: const TextStyle(
      color: const Color(0x8a000000),
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    button: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    subtitle: const TextStyle(
      color: const Color(0xff000000),
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    overline: const TextStyle(
      color: const Color(0xff000000),
      fontSize: 10.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
  ),
  primaryTextTheme: const TextTheme(
    display4: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 96.0,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
    ),
    display3: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 60.0,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
    ),
    display2: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 48.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    display1: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 34.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    headline: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 24.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    title: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 20.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    subhead: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    body2: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    body1: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    caption: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    button: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    subtitle: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    overline: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 10.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
  ),
  accentTextTheme: const TextTheme(
    display4: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 96.0,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
    ),
    display3: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 60.0,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
    ),
    display2: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 48.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    display1: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 34.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    headline: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 24.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    title: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 20.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    subhead: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    body2: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    body1: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    caption: const TextStyle(
      color: const Color(0xb3ffffff),
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    button: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    subtitle: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
    overline: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 10.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
  ),
  inputDecorationTheme: const InputDecorationTheme(
    labelStyle: const TextStyle(
      color: const Color(0xffffc266),
      fontSize: 13.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.italic,
    ),
    helperStyle: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    hintStyle: const TextStyle(
      color: const Color(0xffc5c5c5),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    errorStyle: const TextStyle(
      color: const Color(0xddff0000),
      fontSize: 13.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    errorMaxLines: null,
    hasFloatingPlaceholder: true,
    isDense: false,
    contentPadding: const EdgeInsets.only(top: 0.0, bottom: 0.0, left: 0.0, right: 0.0),
    isCollapsed: true,
    prefixStyle: const TextStyle(
      color: const Color(0xff808080),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    suffixStyle: const TextStyle(
      color: const Color(0xff828282),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    counterStyle: const TextStyle(
      color: const Color(0xdd000000),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    filled: false,
    fillColor: const Color(0x00000000),
    errorBorder: const UnderlineInputBorder(
      borderSide: const BorderSide(
        color: const Color(0xff000000),
        width: 1.0,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    focusedBorder: const UnderlineInputBorder(
      borderSide: const BorderSide(
        color: const Color(0xff000000),
        width: 1.0,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    focusedErrorBorder: const UnderlineInputBorder(
        borderSide: const BorderSide(
          color: const Color(0xff000000),
          width: 2.0,
          style: BorderStyle.solid,
        ),
        borderRadius: BorderRadius.all(Radius.circular(4.0))),
    disabledBorder: const UnderlineInputBorder(
      borderSide: const BorderSide(
        color: const Color(0xff000000),
        width: 1.0,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    enabledBorder: const UnderlineInputBorder(
      borderSide: const BorderSide(
        color: const Color(0xff000000),
        width: 1.0,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    border: const UnderlineInputBorder(
      borderSide: const BorderSide(
        color: const Color(0xff000000),
        width: 1.0,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
  ),
  iconTheme: const IconThemeData(
    color: const Color(0xdd000000),
    opacity: 1.0,
    size: 24.0,
  ),
  primaryIconTheme: const IconThemeData(
    color: const Color(0xffffffff),
    opacity: 1.0,
    size: 24.0,
  ),
  accentIconTheme: const IconThemeData(
    color: const Color(0xffffffff),
    opacity: 1.0,
    size: 24.0,
  ),
  sliderTheme: const SliderThemeData(
    activeTrackColor: const Color(0xffff4915),
    inactiveTrackColor: const Color(0x3dff4915),
    disabledActiveTrackColor: const Color(0x52992200),
    disabledInactiveTrackColor: const Color(0x1f992200),
    activeTickMarkColor: const Color(0x8affd7cc),
    inactiveTickMarkColor: const Color(0x8aff4915),
    disabledActiveTickMarkColor: const Color(0x1fffd7cc),
    disabledInactiveTickMarkColor: const Color(0x1f992200),
    thumbColor: const Color(0xffff4915),
    disabledThumbColor: const Color(0x52992200),
    thumbShape: RoundSliderThumbShape(),
    overlayColor: const Color(0x29ff4915),
    valueIndicatorColor: const Color(0xffff4915),
    valueIndicatorShape: const PaddleSliderValueIndicatorShape(),
    showValueIndicator: ShowValueIndicator.onlyForDiscrete,
    valueIndicatorTextStyle: const TextStyle(
      color: const Color(0xffffffff),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
  ),
  tabBarTheme: const TabBarTheme(
    indicatorSize: TabBarIndicatorSize.tab,
    labelColor: const Color(0xffffffff),
    unselectedLabelColor: const Color(0xb2ffffff),
  ),
  chipTheme: const ChipThemeData(
    selectedShadowColor: const Color(0xffff9800),
    backgroundColor: const Color(0xffd9d9d9),
    brightness: Brightness.light,
    deleteIconColor: const Color(0xde000000),
    disabledColor: const Color(0xffeaeaea),
    labelPadding: const EdgeInsets.only(top: 0.0, bottom: 0.0, left: 8.0, right: 8.0),
    labelStyle: const TextStyle(
      color: const Color(0xff000000),
      fontSize: 12.0,
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
    ),
    padding: const EdgeInsets.only(top: 4.0, bottom: 4.0, left: 4.0, right: 4.0),
    secondaryLabelStyle: const TextStyle(
      color: const Color(0xff000000),
      fontSize: 12.0,
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
    ),
    secondarySelectedColor: const Color(0xffff9800),
    selectedColor: const Color(0xffff9800),
    shape: const StadiumBorder(
        side: const BorderSide(
      color: const Color(0xff000000),
      width: 0.0,
      style: BorderStyle.none,
    )),
  ),
  dialogTheme: const DialogTheme(
      shape: RoundedRectangleBorder(
    side: const BorderSide(
      color: const Color(0xff000000),
      width: 0.0,
      style: BorderStyle.none,
    ),
    borderRadius: BorderRadius.all(Radius.circular(0.0)),
  )),
);
